import { task, usePlugin } from "@nomiclabs/buidler/config";
import { GreeterContract, GreeterInstance } from 'typechain';

usePlugin("@nomiclabs/buidler-truffle5");

task("testme", "", async (taskArgs, bre) => {
  const Greeter: GreeterContract = bre.artifacts.require('Greeter')
  const greeter: GreeterInstance = await Greeter.new('Hello!')

  const greeting: string = await greeter.greet()
  console.log(`Greeter says: ${greeting}`)

  // Here's the problem.
  // If you want to use Truffle types at a lower level
  // than those generated by Typechain, you need to install
  // truffle-typings, since that seems to be what is exended in
  // typechain/index.d.ts.
  // Unless truffle-typings 1.0.4 is installed, the following error is thrown:
  /* node_modules/truffle-typings/index.d.ts:8:21 - error TS1340: Module 'web3' does not refer to a type, but is used as a type here. Did you mean 'typeof import('web3')'? */

/* 8 declare type Web3 = import("web3"); */
  const anotherGreeter: Truffle.ContractInstance = await Greeter.new('Howdy ;D')
  console.log(`Another greeter deployed at ${anotherGreeter.address}`)
});

export default {};
